language: csharp
solution: MC-33.sln
mono: latest
dotnet: 3.0

jobs:
  include:
    - dotnet: 3.0
      mono: latest

install:
 - dotnet restore

script:
 - dotnet build
 - dotnet test MC-33-Tests/MC-33-Tests.csproj